# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Pipeline YAML para configurar e instalar Apache en una máquina virtual
# Este pipeline instala y configura Apache en una máquina virtual Ubuntu.

trigger:
- main

stages:
- stage: DeployToVM
  jobs: 
  - deployment: InstallApacheAndConfigure
    displayName: "Instalar Apache y Configurar Página"

    environment: 
      name: "Admin-Vm-Grupo5"
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Probando conexion"
              
            displayName: 'Instalación y configuración de Apache'
